In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
import os
import pandas as pd


drive_base_path = '/content/drive/My Drive/'

files = os.listdir(drive_base_path)
print(files)

['EBSCO', 'Colab Notebooks', 'Untitled0.ipynb', 'Slides', 'Linear_Ridge_Lasso Regression_092623.ipynb', 'Untitled', 'GR5067_Group3.pptx', 'DA file ', 'firstpresentation-nlp.gslides', 'nlp final paper.gdoc', 'CherieXu_Resume.pdf', 'NLP-coursework', 'time series - coursework', 'Data viz final project', 'Priceline project activity log - Cherie.gsheet', 'Accountant for Consultant', 'Notability backup']

In [ ]:
folder_path = '/content/drive/My Drive/Data viz final project/LCA_Data'
files_in_folder = os.listdir(folder_path)
print(files_in_folder)

['LCA_Disclosure_Data_FY2023_Q4.xlsx', 'LCA_Disclosure_Data_FY2023_Q1.xlsx', 'LCA_Disclosure_Data_FY2022_Q1.xlsx', 'LCA_Disclosure_Data_FY2022_Q2.xlsx', 'LCA_Disclosure_Data_FY2022_Q4.xlsx', 'LCA_Disclosure_Data_FY2023_Q3.xlsx', 'LCA_Disclosure_Data_FY2022_Q3.xlsx', 'LCA_Disclosure_Data_FY2021_Q1.xlsx', 'LCA_Disclosure_Data_FY2021_Q4.xlsx', 'LCA_Disclosure_Data_FY2023_Q2.xlsx', 'LCA_Disclosure_Data_FY2020_Q1.xlsx', 'LCA_Disclosure_Data_FY2020_Q2.xlsx', 'LCA_Disclosure_Data_FY2020_Q3.xlsx', 'LCA_Disclosure_Data_FY2020_Q4.xlsx', 'LCA_Disclosure_Data_FY2021_Q2.xlsx', 'LCA_Disclosure_Data_FY2021_Q3.xlsx', 'H-1B_Disclosure_Data_FY2019.xlsx', 'combined_data.csv', 'Data_Merge.ipynb', 'LCA_2020-2023.csv', 'LCA2019.csv', 'LCA2019-2023.csv']

In [ ]:
 #selected cols only
 # will add a few more cols for need
 cols_to_load = ['RECEIVED_DATE','DECISION_DATE','ORIGINAL_CERT_DATE','VISA_CLASS','JOB_TITLE', 'CASE_STATUS','SOC_TITLE','FULL_TIME_POSITION',
                 'BEGIN_DATE','END_DATE','EMPLOYER_NAME','EMPLOYER_CITY','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','NAICS_CODE',
                 'WAGE_RATE_OF_PAY_FROM','WAGE_RATE_OF_PAY_TO','WAGE_UNIT_OF_PAY','PREVAILING_WAGE','PW_UNIT_OF_PAY','PW_WAGE_LEVEL',
                 'WORKSITE_CITY','CASE_STATUS','WORKSITE_POSTAL_CODE']

In [ ]:
#2023
file_path_2023_Q4 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2023_Q4.xlsx')
df_2023_Q4 = pd.read_excel(file_path_2023_Q4, usecols=cols_to_load)

file_path_2023_Q3 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2023_Q3.xlsx')
df_2023_Q3 = pd.read_excel(file_path_2023_Q3, usecols=cols_to_load)

file_path_2023_Q2 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2023_Q2.xlsx')
df_2023_Q2 = pd.read_excel(file_path_2023_Q2, usecols=cols_to_load)

file_path_2023_Q1 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2023_Q1.xlsx')
df_2023_Q1 = pd.read_excel(file_path_2023_Q1, usecols=cols_to_load)


#2022
file_path_2022_Q4 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2022_Q4.xlsx')
df_2022_Q4 = pd.read_excel(file_path_2022_Q4, usecols=cols_to_load)

file_path_2022_Q3 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2022_Q3.xlsx')
df_2022_Q3 = pd.read_excel(file_path_2022_Q3, usecols=cols_to_load)

file_path_2022_Q2 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2022_Q2.xlsx')
df_2022_Q2 = pd.read_excel(file_path_2022_Q2, usecols=cols_to_load)

file_path_2022_Q1 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2022_Q1.xlsx')
df_2022_Q1 = pd.read_excel(file_path_2022_Q1, usecols=cols_to_load)

#2021
file_path_2021_Q1 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2021_Q1.xlsx')
df_2021_Q1 = pd.read_excel(file_path_2021_Q1, usecols=cols_to_load)

file_path_2021_Q2 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2021_Q2.xlsx')
df_2021_Q2 = pd.read_excel(file_path_2021_Q2, usecols=cols_to_load)

file_path_2021_Q3 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2021_Q3.xlsx')
df_2021_Q3 = pd.read_excel(file_path_2021_Q3, usecols=cols_to_load)

file_path_2021_Q4 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2021_Q4.xlsx')
df_2021_Q4 = pd.read_excel(file_path_2021_Q4, usecols=cols_to_load)



file_path_2020_Q1 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2020_Q1.xlsx')
df_2020_Q1 = pd.read_excel(file_path_2020_Q1, usecols=cols_to_load)

file_path_2020_Q2 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2020_Q2.xlsx')
df_2020_Q2 = pd.read_excel(file_path_2020_Q2, usecols=cols_to_load)

file_path_2020_Q3 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2020_Q3.xlsx')
df_2020_Q3 = pd.read_excel(file_path_2020_Q3, usecols=cols_to_load)

file_path_2020_Q4 = os.path.join(folder_path, 'LCA_Disclosure_Data_FY2020_Q4.xlsx')
df_2020_Q4 = pd.read_excel(file_path_2020_Q4, usecols=cols_to_load)

In [ ]:
# combine 2020-2023 Q files
combined_df = pd.concat([df_2020_Q1,df_2020_Q2,df_2020_Q3,df_2020_Q4,df_2021_Q1,df_2021_Q2,df_2021_Q3,df_2021_Q4,df_2022_Q1,df_2022_Q2,df_2022_Q3,df_2022_Q4,df_2023_Q1,df_2023_Q2,df_2023_Q3,df_2023_Q4],
                         ignore_index=True)

In [ ]:
print(combined_df)

                   CASE_STATUS RECEIVED_DATE DECISION_DATE ORIGINAL_CERT_DATE  \
0                    Certified    2019-09-25    2019-10-01                NaT
1                    Certified    2019-09-25    2019-10-01                NaT
2                    Certified    2019-09-25    2019-10-01                NaT
3                    Certified    2019-09-25    2019-10-01                NaT
4                    Certified    2019-09-25    2019-10-01                NaT
...                        ...           ...           ...                ...
2674325              Withdrawn    2023-06-29    2023-07-02                NaT
2674326              Withdrawn    2023-06-29    2023-07-02                NaT
2674327              Withdrawn    2023-06-28    2023-07-02                NaT
2674328  Certified - Withdrawn    2021-07-30    2023-07-01         2021-08-06
2674329  Certified - Withdrawn    2021-07-13    2023-07-01         2021-07-20

        VISA_CLASS                               JOB_TITLE  \
0             H-1B  APPLICATION ENGINEER, OMS [15-1199.02]
1             H-1B                         BI DEVELOPER II
2             H-1B                        QUALITY ENGINEER
3             H-1B        SOFTWARE DEVELOPER, APPLICATIONS
4             H-1B               QUALITY ENGINEER LEVEL II
...            ...                                     ...
2674325       H-1B                    Full Stack Developer
2674326       H-1B                    Full Stack Developer
2674327       H-1B    Software Engineer - Data & Analytics
2674328       H-1B                       Software Engineer
2674329       H-1B                    Software Engineer II

                                 SOC_TITLE FULL_TIME_POSITION BEGIN_DATE  \
0          COMPUTER OCCUPATIONS, ALL OTHER                  Y 2019-10-07
1        SOFTWARE DEVELOPERS, APPLICATIONS                  Y 2020-01-08
2                     MECHANICAL ENGINEERS                  Y 2019-10-03
3        SOFTWARE DEVELOPERS, APPLICATIONS                  Y 2019-10-07
4          COMPUTER OCCUPATIONS, ALL OTHER                  Y 2019-10-09
...                                    ...                ...        ...
2674325                Software Developers                  Y 2023-07-10
2674326                Software Developers                  Y 2023-07-10
2674327                Software Developers                  Y 2023-07-03
2674328  Software Developers, Applications                  Y 2021-08-16
2674329  Software Developers, Applications                  Y 2021-08-16

          END_DATE  ... EMPLOYER_POSTAL_CODE NAICS_CODE WORKSITE_CITY  \
0       2022-10-07  ...                44236     451120        Hudson
1       2023-01-07  ...                92618     541512     BRENTWOOD
2       2022-10-02  ...                48033     541511      Dearborn
3       2022-10-01  ...                48084     541511        Taylor
4       2022-10-08  ...                50325     541511      BLUE ASH
...            ...  ...                  ...        ...           ...
2674325 2025-09-30  ...                75067      54151       Houston
2674326 2025-09-30  ...                75067      54151       Houston
2674327 2024-04-25  ...                60173     541511    Schaumburg
2674328 2024-08-15  ...                95110     541519     Sunnyvale
2674329 2024-08-15  ...                10016     541990      Bellevue

        WORKSITE_POSTAL_CODE  WAGE_RATE_OF_PAY_FROM WAGE_RATE_OF_PAY_TO  \
0                      44224              100000.00                 NaN
1                      37027                  38.57               38.57
2                      48126                  43.50                 NaN
3                      48180                  57.69               57.69
4                      45242               75000.00                 NaN
...                      ...                    ...                 ...
2674325                77002               98904.00           120000.00
2674326                77002               98904.00           120000.00
2674327                60173              134118.00           134120.00
2674328                94085              147680.00                 NaN
2674329                98004              162510.00           203000.00

        WAGE_UNIT_OF_PAY  PREVAILING_WAGE  PW_UNIT_OF_PAY PW_WAGE_LEVEL
0                   Year          95118.0            Year            IV
1                   Hour             39.0            Hour            II
2                   Hour             39.0            Hour            II
3                   Hour             53.0            Hour            IV
4                   Year          65333.0            Year            II
...                  ...              ...             ...           ...
2674325             Year          90522.0            Year            II
2674326             Year          90522.0            Year            II
2674327             Year         134118.0            Year            IV
2674328             Year         130894.0            Year            II
2674329             Year         162510.0            Year            IV

[2674330 rows x 23 columns]

In [ ]:
#export merge data 2020-2023
combined_df.to_csv('/content/drive/My Drive/Data viz final project/LCA_Data/LCA_2020-2023.csv', index=False)
print("save sucess:'/content/drive/My Drive/Data viz final project/LCA_Data/LCA_2020-2022.csv'")

save sucess:'/content/drive/My Drive/Data viz final project/LCA_Data/LCA_2020-2022.csv'

In [ ]:
# read 2020-2023 merge data
file_path_c= os.path.join(folder_path, 'LCA_2020-2023.csv')
df_c = pd.read_csv(file_path_c)

<ipython-input-11-0dc9f157fd76>:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_c = pd.read_csv(file_path_c)

In [ ]:
# read 2019 individually
file_path_2019 = os.path.join(folder_path, 'H-1B_Disclosure_Data_FY2019.xlsx')
df_2019 = pd.read_excel(file_path_2019, engine='openpyxl')

In [ ]:
print(df_2019)

In [ ]:
selected_cols_df_2019 = df_2019[['EMPLOYER_NAME', 'NAICS_CODE', 'VISA_CLASS', 'SOC_TITLE', 'EMPLOYER_POSTAL_CODE', 'FULL_TIME_POSITION', 'EMPLOYER_STATE', 'EMPLOYER_CITY', 'ORIGINAL_CERT_DATE', 'DECISION_DATE', 'JOB_TITLE',
'CASE_SUBMITTED', 'PERIOD_OF_EMPLOYMENT_START_DATE', 'PERIOD_OF_EMPLOYMENT_END_DATE', 'WAGE_RATE_OF_PAY_FROM_1','WAGE_RATE_OF_PAY_TO_1', 'WAGE_UNIT_OF_PAY_1', "PREVAILING_WAGE_1","PW_UNIT_OF_PAY_1", 'PW_WAGE_LEVEL_1',
                'WORKSITE_CITY_1','WORKSITE_POSTAL_CODE_1','CASE_STATUS']]


#selected_cols_df_2019 = df_2019[['EMPLOYER_NAME', 'NAICS_CODE', 'VISA_CLASS', 'SOC_TITLE', 'EMPLOYER_POSTAL_CODE', 'FULL_TIME_POSITION', 'EMPLOYER_STATE', 'EMPLOYER_CITY', 'ORIGINAL_CERT_DATE', 'DECISION_DATE', 'JOB_TITLE',
#'CASE_SUBMITTED', 'PERIOD_OF_EMPLOYMENT_START_DATE', 'PERIOD_OF_EMPLOYMENT_END_DATE','WAGE_RATE_OF_PAY_FROM_1','WAGE_RATE_OF_PAY_TO_1', 'WAGE_UNIT_OF_PAY_1', "PREVAILING_WAGE_1","PW_UNIT_OF_PAY_1", 'PW_WAGE_LEVEL_1']]

In [ ]:
selected_cols_df_2019.to_csv('/content/drive/My Drive/Data viz final project/LCA_Data/LCA2019.csv', index=False)
#print("save sucess:'/content/drive/My Drive/Data viz final project/LCA_Data/LCA2019.csv'")

In [ ]:
#df_2019.to_csv('/content/drive/My Drive/Data viz final project/LCA_Data/LCA2019.csv', index=False)
#print("save sucess:'/content/drive/My Drive/Data viz final project/LCA_Data/LCA2019.csv'")

In [ ]:
file_path_c19= os.path.join(folder_path, 'LCA2019.csv')
df_c19 = pd.read_csv(file_path_c19)

In [ ]:
print(df_c19)

                                   EMPLOYER_NAME  NAICS_CODE      VISA_CLASS  \
0                         R/GA MEDIA GROUP, INC.    541810.0            H-1B
1                          MOTHER INDUSTRIES LLC    541810.0  E-3 Australian
2                         WE ARE UNLIMITED, INC.    541810.0  E-3 Australian
3                            HELLO ELEPHANT, LLC    541810.0  E-3 Australian
4                            HELLO ELEPHANT, LLC    541810.0  E-3 Australian
...                                          ...         ...             ...
664611  AMERICAN FAMILY MUTUAL INSURANCE COMPANY    524113.0            H-1B
664612                     CAPGEMINI AMERICA INC      5416.0            H-1B
664613                     CAPGEMINI AMERICA INC      5416.0            H-1B
664614                     CAPGEMINI AMERICA INC      5416.0            H-1B
664615                     CAPGEMINI AMERICA INC      5416.0            H-1B

                                  SOC_TITLE EMPLOYER_POSTAL_CODE  \
0       ADVERTISING AND PROMOTIONS MANAGERS                10001
1       ADVERTISING AND PROMOTIONS MANAGERS                10036
2       ADVERTISING AND PROMOTIONS MANAGERS                60601
3       ADVERTISING AND PROMOTIONS MANAGERS                11201
4       ADVERTISING AND PROMOTIONS MANAGERS                11201
...                                     ...                  ...
664611                              15-2031                53783
664612                                  NaN                60606
664613                                  NaN                60606
664614                                  NaN                60606
664615                                  NaN                60606

       FULL_TIME_POSITION EMPLOYER_STATE EMPLOYER_CITY ORIGINAL_CERT_DATE  \
0                       Y             NY      NEW YORK                NaN
1                       Y             NY      NEW YORK                NaN
2                       Y             IL       CHICAGO                NaN
3                       Y             NY      BROOKLYN                NaN
4                       Y             NY      BROOKLYN                NaN
...                   ...            ...           ...                ...
664611                  Y             WI       MADISON                NaN
664612                  Y             IL       CHICAGO                NaN
664613                  Y             IL       CHICAGO                NaN
664614                  Y             IL       CHICAGO                NaN
664615                  Y             IL       CHICAGO                NaN

              DECISION_DATE  ... PERIOD_OF_EMPLOYMENT_END_DATE  \
0       2019-04-30 00:00:00  ...           2019-09-30 00:00:00
1       2019-05-13 00:00:00  ...           2019-10-01 00:00:00
2       2019-04-30 00:00:00  ...           2019-09-11 00:00:00
3       2019-08-20 00:00:00  ...           2020-01-07 00:00:00
4       2019-04-15 00:00:00  ...           2020-02-01 00:00:00
...                     ...  ...                           ...
664611  2018-10-15 22:00:43  ...                    10/17/2021
664612  2019-02-22 10:45:38  ...           2022-08-16 00:00:00
664613  2019-03-07 16:07:41  ...           2022-08-29 00:00:00
664614  2019-03-08 12:01:58  ...           2022-09-02 00:00:00
664615  2019-03-19 11:41:04  ...           2022-03-13 00:00:00

       WAGE_RATE_OF_PAY_FROM_1 WAGE_RATE_OF_PAY_TO_1 WAGE_UNIT_OF_PAY_1  \
0                     179000.0              189000.0               Year
1                     110000.0              130000.0               Year
2                     275000.0              325000.0               Year
3                     140000.0              170000.0               Year
4                     180000.0              210000.0               Year
...                        ...                   ...                ...
664611                 85500.0                   NaN               Year
664612                 80800.0                   NaN               Year
664613                 74500.0                   NaN               Year
664614                 75900.0                   NaN               Year
664615                 66700.0                   NaN               Year

        PREVAILING_WAGE_1  PW_UNIT_OF_PAY_1 PW_WAGE_LEVEL_1  WORKSITE_CITY_1  \
0                     NaN               NaN             NaN         NEW YORK
1                     NaN               NaN             NaN         NEW YORK
2                     NaN               NaN             NaN          CHICAGO
3                     NaN               NaN             NaN         BROOKLYN
4                     NaN               NaN             NaN         BROOKLYN
...                   ...               ...             ...              ...
664611            75733.0              Year       Level III          MADISON
664612            80704.0              Year        Level II         DEARBORN
664613            74443.0              Year        Level II         NEW YORK
664614            75858.0              Year       Level III        NASHVILLE
664615            66643.0              Year        Level II          MADISON

       WORKSITE_POSTAL_CODE_1 CASE_STATUS
0                       10001   WITHDRAWN
1                       10036   WITHDRAWN
2                       60601   WITHDRAWN
3                       11201   WITHDRAWN
4                       11201   WITHDRAWN
...                       ...         ...
664611                  53783   CERTIFIED
664612                  48126      DENIED
664613                  10019      DENIED
664614                  37214      DENIED
664615                  53783      DENIED

[664616 rows x 23 columns]

In [ ]:
#rename column

df_c19.rename(columns= {'CASE_SUBMITTED':'RECEIVED_DATE', 'PERIOD_OF_EMPLOYMENT_START_DATE': 'BEGIN_DATE', 'PERIOD_OF_EMPLOYMENT_END_DATE':'END_DATE',
                       'WAGE_RATE_OF_PAY_FROM_1': 'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO_1':'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY_1':'WAGE_UNIT_OF_PAY',
                       'PREVAILING_WAGE_1':'PREVAILING_WAGE', 'PW_UNIT_OF_PAY_1':'PW_UNIT_OF_PAY','PW_WAGE_LEVEL_1':'PW_WAGE_LEVEL','WORKSITE_CITY_1':'WORKSITE_CITY','WORKSITE_POSTAL_CODE_1': 'WORKSITE_POSTAL_CODE'}, inplace=True)

In [ ]:
print(df_c19)

In [ ]:
print(df_c)

                   CASE_STATUS RECEIVED_DATE DECISION_DATE ORIGINAL_CERT_DATE  \
0                    Certified    2019-09-25    2019-10-01                NaN
1                    Certified    2019-09-25    2019-10-01                NaN
2                    Certified    2019-09-25    2019-10-01                NaN
3                    Certified    2019-09-25    2019-10-01                NaN
4                    Certified    2019-09-25    2019-10-01                NaN
...                        ...           ...           ...                ...
2674325              Withdrawn    2023-06-29    2023-07-02                NaN
2674326              Withdrawn    2023-06-29    2023-07-02                NaN
2674327              Withdrawn    2023-06-28    2023-07-02                NaN
2674328  Certified - Withdrawn    2021-07-30    2023-07-01         2021-08-06
2674329  Certified - Withdrawn    2021-07-13    2023-07-01         2021-07-20

        VISA_CLASS                               JOB_TITLE  \
0             H-1B  APPLICATION ENGINEER, OMS [15-1199.02]
1             H-1B                         BI DEVELOPER II
2             H-1B                        QUALITY ENGINEER
3             H-1B        SOFTWARE DEVELOPER, APPLICATIONS
4             H-1B               QUALITY ENGINEER LEVEL II
...            ...                                     ...
2674325       H-1B                    Full Stack Developer
2674326       H-1B                    Full Stack Developer
2674327       H-1B    Software Engineer - Data & Analytics
2674328       H-1B                       Software Engineer
2674329       H-1B                    Software Engineer II

                                 SOC_TITLE FULL_TIME_POSITION  BEGIN_DATE  \
0          COMPUTER OCCUPATIONS, ALL OTHER                  Y  2019-10-07
1        SOFTWARE DEVELOPERS, APPLICATIONS                  Y  2020-01-08
2                     MECHANICAL ENGINEERS                  Y  2019-10-03
3        SOFTWARE DEVELOPERS, APPLICATIONS                  Y  2019-10-07
4          COMPUTER OCCUPATIONS, ALL OTHER                  Y  2019-10-09
...                                    ...                ...         ...
2674325                Software Developers                  Y  2023-07-10
2674326                Software Developers                  Y  2023-07-10
2674327                Software Developers                  Y  2023-07-03
2674328  Software Developers, Applications                  Y  2021-08-16
2674329  Software Developers, Applications                  Y  2021-08-16

           END_DATE  ... EMPLOYER_POSTAL_CODE NAICS_CODE WORKSITE_CITY  \
0        2022-10-07  ...                44236     451120        Hudson
1        2023-01-07  ...                92618     541512     BRENTWOOD
2        2022-10-02  ...                48033     541511      Dearborn
3        2022-10-01  ...                48084     541511        Taylor
4        2022-10-08  ...                50325     541511      BLUE ASH
...             ...  ...                  ...        ...           ...
2674325  2025-09-30  ...                75067      54151       Houston
2674326  2025-09-30  ...                75067      54151       Houston
2674327  2024-04-25  ...                60173     541511    Schaumburg
2674328  2024-08-15  ...                95110     541519     Sunnyvale
2674329  2024-08-15  ...                10016     541990      Bellevue

        WORKSITE_POSTAL_CODE  WAGE_RATE_OF_PAY_FROM WAGE_RATE_OF_PAY_TO  \
0                      44224              100000.00                 NaN
1                      37027                  38.57               38.57
2                      48126                  43.50                 NaN
3                      48180                  57.69               57.69
4                      45242               75000.00                 NaN
...                      ...                    ...                 ...
2674325                77002               98904.00           120000.00
2674326                77002               98904.00           120000.00
2674327                60173              134118.00           134120.00
2674328                94085              147680.00                 NaN
2674329                98004              162510.00           203000.00

        WAGE_UNIT_OF_PAY  PREVAILING_WAGE  PW_UNIT_OF_PAY PW_WAGE_LEVEL
0                   Year          95118.0            Year            IV
1                   Hour             39.0            Hour            II
2                   Hour             39.0            Hour            II
3                   Hour             53.0            Hour            IV
4                   Year          65333.0            Year            II
...                  ...              ...             ...           ...
2674325             Year          90522.0            Year            II
2674326             Year          90522.0            Year            II
2674327             Year         134118.0            Year            IV
2674328             Year         130894.0            Year            II
2674329             Year         162510.0            Year            IV

[2674330 rows x 23 columns]

In [ ]:
# merge two dataframe together and export

df_19_23 = pd.concat([df_c, df_c19])

df_19_23.reset_index(drop=True, inplace=True)


df_19_23.to_csv('/content/drive/My Drive/Data viz final project/LCA_Data/LCA2019-2023.csv', index=False)

In [ ]:
print(df_19_23)

        CASE_STATUS        RECEIVED_DATE        DECISION_DATE  \
0         Certified           2019-09-25           2019-10-01
1         Certified           2019-09-25           2019-10-01
2         Certified           2019-09-25           2019-10-01
3         Certified           2019-09-25           2019-10-01
4         Certified           2019-09-25           2019-10-01
...             ...                  ...                  ...
3338941   CERTIFIED  2018-10-09 18:10:32  2018-10-15 22:00:43
3338942      DENIED  2019-02-15 16:53:11  2019-02-22 10:45:38
3338943      DENIED  2019-02-28 01:11:11  2019-03-07 16:07:41
3338944      DENIED  2019-03-04 08:37:04  2019-03-08 12:01:58
3338945      DENIED  2019-03-14 08:14:46  2019-03-19 11:41:04

        ORIGINAL_CERT_DATE VISA_CLASS                               JOB_TITLE  \
0                      NaN       H-1B  APPLICATION ENGINEER, OMS [15-1199.02]
1                      NaN       H-1B                         BI DEVELOPER II
2                      NaN       H-1B                        QUALITY ENGINEER
3                      NaN       H-1B        SOFTWARE DEVELOPER, APPLICATIONS
4                      NaN       H-1B               QUALITY ENGINEER LEVEL II
...                    ...        ...                                     ...
3338941                NaN       H-1B             DIGITAL TOUCHPOINTS ANALYST
3338942                NaN       H-1B               APPLICATIONS CONSULTANT 2
3338943                NaN       H-1B              BUSINESS SYSTEMS ANALYST 2
3338944                NaN       H-1B               APPLICATIONS CONSULTANT 2
3338945                NaN       H-1B              BUSINESS SYSTEMS ANALYST 2

                                 SOC_TITLE FULL_TIME_POSITION  \
0          COMPUTER OCCUPATIONS, ALL OTHER                  Y
1        SOFTWARE DEVELOPERS, APPLICATIONS                  Y
2                     MECHANICAL ENGINEERS                  Y
3        SOFTWARE DEVELOPERS, APPLICATIONS                  Y
4          COMPUTER OCCUPATIONS, ALL OTHER                  Y
...                                    ...                ...
3338941                            15-2031                  Y
3338942                                NaN                  Y
3338943                                NaN                  Y
3338944                                NaN                  Y
3338945                                NaN                  Y

                  BEGIN_DATE             END_DATE  ... EMPLOYER_POSTAL_CODE  \
0                 2019-10-07           2022-10-07  ...                44236
1                 2020-01-08           2023-01-07  ...                92618
2                 2019-10-03           2022-10-02  ...                48033
3                 2019-10-07           2022-10-01  ...                48084
4                 2019-10-09           2022-10-08  ...                50325
...                      ...                  ...  ...                  ...
3338941           10/17/2018           10/17/2021  ...                53783
3338942  2019-08-17 00:00:00  2022-08-16 00:00:00  ...                60606
3338943  2019-08-30 00:00:00  2022-08-29 00:00:00  ...                60606
3338944  2019-09-03 00:00:00  2022-09-02 00:00:00  ...                60606
3338945  2019-03-14 00:00:00  2022-03-13 00:00:00  ...                60606

        NAICS_CODE WORKSITE_CITY WORKSITE_POSTAL_CODE  WAGE_RATE_OF_PAY_FROM  \
0         451120.0        Hudson                44224              100000.00
1         541512.0     BRENTWOOD                37027                  38.57
2         541511.0      Dearborn                48126                  43.50
3         541511.0        Taylor                48180                  57.69
4         541511.0      BLUE ASH                45242               75000.00
...            ...           ...                  ...                    ...
3338941   524113.0       MADISON                53783               85500.00
3338942     5416.0      DEARBORN                48126               80800.00
3338943     5416.0      NEW YORK                10019               74500.00
3338944     5416.0     NASHVILLE                37214               75900.00
3338945     5416.0       MADISON                53783               66700.00

        WAGE_RATE_OF_PAY_TO WAGE_UNIT_OF_PAY  PREVAILING_WAGE  PW_UNIT_OF_PAY  \
0                       NaN             Year          95118.0            Year
1                     38.57             Hour             39.0            Hour
2                       NaN             Hour             39.0            Hour
3                     57.69             Hour             53.0            Hour
4                       NaN             Year          65333.0            Year
...                     ...              ...              ...             ...
3338941                 NaN             Year          75733.0            Year
3338942                 NaN             Year          80704.0            Year
3338943                 NaN             Year          74443.0            Year
3338944                 NaN             Year          75858.0            Year
3338945                 NaN             Year          66643.0            Year

        PW_WAGE_LEVEL
0                  IV
1                  II
2                  II
3                  IV
4                  II
...               ...
3338941     Level III
3338942      Level II
3338943      Level II
3338944     Level III
3338945      Level II

[3338946 rows x 23 columns]

In [ ]:
#EDA

n = len(pd.unique(df_19_23['WAGE_UNIT_OF_PAY']))
print(n)

6